version: '3.8'
services:
  pytorch:
    container_name: Trainer
    image: 6d_temp:0.1
    ulimits:
      stack: 67108864
      memlock: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: 
                - gpu
                - utility # nvidia-smi
                - compute # CUDA
                - video #encoding etc
    #runtime: nvidia
    shm_size: '20gb'
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: '1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: gpu,compute,video,utility,graphics
    volumes:
      - G:\00AA_Master_Studium\Projekt\Git\6d_inf_prf\ffb6d\new_model:/workspace/dd6d
      - G:\00AA_Master_Studium\Projekt\Dataset\unzip:/workspace/YCB_Video_Dataset
    network_mode: host
    stdin_open: true
    privileged: true
    command: tail -f /dev/null

#ln -s /workspace/YCB_Video_Dataset /workspace/dd6d/datasets/ycb/ einmalig zum symlink anlegen